language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: gynFa7l/noELHpB/G4qU2iSsqT6T0CFJOR9i4yHMaumyMBZ3o3Qf+E+ITdbkR+gpDte+K4hMeWrM8TZIQkWOo3oIQ5nJamBBNzAN+ReSVgTXckhgwd4y9nrN8skd7fPZxt4e66D89JlwenrRC3BNI7wzohb/UW1hCiPo7W6BAn9X15GJM7EuUb4zeMttpXabocfHUHJ2PfLZRUjAdSwDXedriho4mNxCxrfOMO7Fa12D7rs2RKFZnou/aPcxF9uJV/4rqqw+HWXFNNU0xptpazOd56DWtITdYvdXVjrNlSSW2wKmTTlq3bTfrc/AdSVj2yRzR65GoqrkyUAaUpZN5THtcNSQvKPxhMVve5f4/YjTIypMUZJoNgPUe0wZiHc+l1odAh1KAICXZmH+qcQmyEEIvxqOOZxyowIUaSEYXC1bKFGyJ4hmtz+0b2csD9YTQ/ab5x1ENEvdFexpgnGc3xnRNbmy4cpq6Qa+5V77FWFBXSr8XYP1zmeVr8KZuZN3DiSPNbwYILkpSudujrnkk27N9JSmF/l5q1cA7f6iaSHlJDm21I0LGwnfj+TId4S7WUAbIBu5shgdWMncdfflZ8fknsa28hOuPHLqIjw0B2bbwhBDb6xqQbGBjzairumhavVOGMXLe9seiJaTTU7EVkEYsa1EwsJdJ2/dUcTJtgk=
  app: floating-crag-60990
  on:
    repo: eako0508/node-shopping-list-integration-tests
